CREATE TABLE IF NOT EXISTS "posts" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  slug TEXT NOT NULL,
  content TEXT NOT NULL,
  created_on INTEGER NOT NULL,
  updated_on INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "users" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  key BLOB NOT NULL,
  created_on INTEGER NOT NULL,
  updated_on INTEGER NOT NULL
);
